caliper:
  blockchain: fabric

name: "myfabric-network"
version: "2"

client:
  organization: PeerOrg
  connection:
    timeout:
      peer:
        endorser: "300"

channels:
  mychannel:
    peers:
      peer1-peerorg:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
      peer2-peerorg:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
      peer3-peerorg:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
      peer4-peerorg:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true

organizations:
  PeerOrg:
    mspid: "PeerOrgMSP"
    peers:
      - "peer1-peerorg"
      - "peer2-peerorg"
      - "peer3-peerorg"
      - "peer4-peerorg"

peers:
  peer1-peerorg:
    url: "grpcs://peer1-peerorg:7051"
    grpcOptions:
      ssl-target-name-override: "peer1-peerorg"
    tlsCACerts:
      path: "../../../fabric-ca/peerorg/peer1/tls-msp/tlscacerts/tls-0-0-0-0-7052.pem"
  peer2-peerorg:
    url: "grpcs://peer2-peerorg:8051"
    grpcOptions:
      ssl-target-name-override: "peer2-peerorg"
    tlsCACerts:
      path: "../../../fabric-ca/peerorg/peer2/tls-msp/tlscacerts/tls-0-0-0-0-7052.pem"
  peer3-peerorg:
    url: "grpcs://peer3-peerorg:9051"
    grpcOptions:
      ssl-target-name-override: "peer3-peerorg"
    tlsCACerts:
      path: "../../../fabric-ca/peerorg/peer3/tls-msp/tlscacerts/tls-0-0-0-0-7052.pem"
  peer4-peerorg:
    url: "grpcs://peer4-peerorg:10051"
    grpcOptions:
      ssl-target-name-override: "peer4-peerorg"
    tlsCACerts:
      path: "../../../fabric-ca/peerorg/peer4/tls-msp/tlscacerts/tls-0-0-0-0-7052.pem"

orderers:
  orderer1-ordererorg:
    url: "grpcs://orderer1-ordererorg:7050"
    grpcOptions:
      ssl-target-name-override: "orderer1-ordererorg"
    tlsCACerts:
      path: "../../../fabric-ca/ordererorg/orderer1/tls-msp/tlscacerts/tls-0-0-0-0-7052.pem"
  orderer2-ordererorg:
    url: "grpcs://orderer2-ordererorg:8050"
    grpcOptions:
      ssl-target-name-override: "orderer2-ordererorg"
    tlsCACerts:
      path: "../../../fabric-ca/ordererorg/orderer2/tls-msp/tlscacerts/tls-0-0-0-0-7052.pem"
  orderer3-ordererorg:
    url: "grpcs://orderer3-ordererorg:9050"
    grpcOptions:
      ssl-target-name-override: "orderer3-ordererorg"
    tlsCACerts:
      path: "../../../fabric-ca/ordererorg/orderer3/tls-msp/tlscacerts/tls-0-0-0-0-7052.pem"
